books = {
    "Core Books": [
        {"title": "Adventure Class Ships", "abbreviation": "ACS"},
        {"title": "Bounty Hunter", "abbreviation": "BH"},
        {"title": "Central Supply Catalogue", "abbreviation": "CSC"},
        {"title": "Core Rulebook", "abbreviation": "CRB"},
        {"title": "Deep Space Exploration Handbook", "abbreviation": "DSEH"},
        {"title": "Element Cruisers", "abbreviation": "EC"},
        {"title": "High Guard", "abbreviation": "HG"},
        {"title": "Navy Campaign Sourcebook", "abbreviation": "NCS"},
        {"title": "Robot Handbook", "abbreviation": "RH"},
        {"title": "Small Craft Catalog", "abbreviation": "SCC"},
        {"title": "Traveller Companion", "abbreviation": "TC"},
        {"title": "Update 2022 FAQ", "abbreviation": "U2FAQ"},
        {"title": "Vehicle Handbook", "abbreviation": "VH"},
        {"title": "World Builder's Handbook", "abbreviation": "WBH"},
    ],
    "Charted Space": [
        {"title": "Aliens of Charted Space 1-3", "abbreviation": "AoCS1-3"},
        {"title": "Behind the Claw", "abbreviation": "BtC"},
        {"title": "Bu and Embla's Guide", "abbreviation": "BaEG"},
        {"title": "Bu and Embla Visit Vrirhlanz", "abbreviation": "BaEVV"},
        {"title": "Reft", "abbreviation": "Re"},
        {"title": "Ships of the Reach", "abbreviation": "SotR"},
        {"title": "Solomani Front", "abbreviation": "SF"},
        {"title": "Spinward Extents", "abbreviation": "SE"},
        {"title": "Sword Worlds", "abbreviation": "SW"},
        {"title": "The Deep and the Dark", "abbreviation": "TDatD"},
        {"title": "The Glorious Empire", "abbreviation": "TGE"},
        {"title": "The Great Rift", "abbreviation": "TGR"},
        {"title": "The Great Rift Book 2", "abbreviation": "TGRB2"},
        {"title": "The Imperial Navy", "abbreviation": "TIN"},
        {"title": "The Third Imperium", "abbreviation": "TTI"},
        {"title": "Touchstone & Afawahisa", "abbreviation": "TaA"},
    ],
    "Journal of the Travellers' Aid Society": [
        {"title": "Journal of the Travellers’ Aid Society 1-15", "abbreviation": "JTAS1-15"}
    ],
    "Adventures": [
        {"title": "The Calixcuel Incident", "abbreviation": "TCI"},
        {"title": "The Cordon Conflict", "abbreviation": "TCC"},
        {"title": "Death Station", "abbreviation": "DS"},
        {"title": "Deepnight Endeavour", "abbreviation": "DE"},
        {"title": "Drinax Companion", "abbreviation": "DC"},
        {"title": "Friends in Dry Places", "abbreviation": "FiDP"},
        {"title": "Gods of Marduk", "abbreviation": "GoM"},
        {"title": "High and Dry", "abbreviation": "HaD"},
        {"title": "Liberty Port", "abbreviation": "LP"},
        {"title": "Lions of Thebus", "abbreviation": "LoT"},
        {"title": "Marooned on Marduk", "abbreviation": "MoM"},
        {"title": "Revolution on Acrid", "abbreviation": "RoA"},
        {"title": "Shadows of Sindal", "abbreviation": "SoS"},
        {"title": "Skandersvik", "abbreviation": "Sk"},
        {"title": "Solomani Adventure 1 – Mysteries on Arcturus Station", "abbreviation": "MoAS"},
        {"title": "Stranded", "abbreviation": "St"},
        {"title": "The Pirates of Drinax", "abbreviation": "TPoD"},
        {"title": "The Trojan Reach", "abbreviation": "TRR"},
    ]
}
