books = {
    "Core Books": [
        {"title": "Adventure Class Ships", "abbreviation": "ACS", "id": "1wUFBl4xf908oJ_Q9UXc_lFrPtnBxRkM4ccQxgxohvSM"},
        {"title": "Bounty Hunter", "abbreviation": "BH", "id": "1_6vAjTjIMDVQbqA88z40awlIl91BE75GMqvrytW5GYM"},
        {"title": "Central Supply Catalogue", "abbreviation": "CSC", "id": "1kjtgIWgcIFF1WIEXYOUC1U5-S1_9qNtKs_QwY668vXo"},
        {"title": "Core Rulebook", "abbreviation": "CRB", "id": "10nyiMW51vsugQepyviZ3L19Gknjs6CBM2poLROvf6pw"},
        {"title": "Deep Space Exploration Handbook", "abbreviation": "DSEH", "id": "14EsuuLykT5ymQv4DRqwwd49_04l9_Y08TL8T8u1pWXk"},
        {"title": "Element Cruisers", "abbreviation": "EC", "id": "1C2gIr1jCHZCupN10uvHeqZY0rzryt_Ao3WzjwiyLs0c"},
        {"title": "High Guard", "abbreviation": "HG", "id": "1eUGP5DCQ6pIfP1_E_3vgEdhdF84n_bXTTAT5og8QwcE"},
        {"title": "Navy Campaign Sourcebook", "abbreviation": "NCS", "id": "1rr_GM1d8fcmXZ7YYIVbeODM2LxM7BTh3XIOJ-sq9u2I"},
        {"title": "Robot Handbook", "abbreviation": "RH", "id": "1ZuPQtoUAMbr9lhvLRIBP39QLoYJScjkEZSP0lVB_kUI"},
        {"title": "Small Craft Catalog", "abbreviation": "SCC", "id": "1IHk8tEyLH6sEfnscr43EGsrQt-3ZRIdeAPxrLVx8kpg"},
        {"title": "Traveller Companion", "abbreviation": "TC", "id": "1trAoMsS1pnHdFs1T1QZBQjOqXLeWBeGsPDAlUdaoA_M"},
        {"title": "Update 2022 FAQ", "abbreviation": "U2FAQ", "id": "1GgVNGU0uOamEgMT3KkhIECGIoOSvndt2rvSTDM1YtvA"},
        {"title": "Vehicle Handbook", "abbreviation": "VH", "id": "1b7SMLyfXZk7PtVyRZw5kiho8maVR2yyvFQdMbgtumqg"},
        {"title": "World Builder's Handbook", "abbreviation": "WBH", "id": "1bIf1QhjVWOkuDKNfhrUU1gXREHGJQtB_-ZbQPqauak8"},
    ],
    "Charted Space": [
        {"title": "Aliens of Charted Space 1", "abbreviation": "AoCS1", "id": "1Mj4_5sLpHJPaRBozbIvJO5gA3Ik1p9SWf3u5eHDz_A4"},
        {"title": "Aliens of Charted Space 2", "abbreviation": "AoCS2", "id": "1QZMOOXdJxt4Su7G8eKuvt2Wr5reRwizNYocJO34PPO8"},
        {"title": "Aliens of Charted Space 3", "abbreviation": "AoCS3", "id": "1f2w5peynvFFe-KA705u7uQrjA3qwwiiytr5pJsBWl88"},
        {"title": "Behind the Claw", "abbreviation": "BtC", "id": "1RJsD_7B-NLjSpeJegnnAFS9RNlmuauCPIF5Ruo2ZCUE"},
        {"title": "Bu and Embla's Guide", "abbreviation": "BaEG", "id": "1fSZSWJsojPm0w5_m37F5SSCo-riyTf1THzIzAeZZ250"},
        {"title": "Bu and Embla Visit Vrirhlanz", "abbreviation": "BaEVV", "id": "1PNl_tOD0M_05EnE8tA3dtkkLYeyT_4xrGSzh7ZyDUp4"},
        {"title": "Referee's Briefing 2 Anomalies and Wonders", "abbreviation": "RB2AaW", "id": "1zXt0Gclvsvk1YiZAGl6CGQntrnrc_3-UVlEsKymXxHc"},
        {"title": "Reft", "abbreviation": "Re", "id": "16B6VqCQF8KFmhivzVPq2AaunYz1AMbVNCsXNqaT620I"},
        {"title": "Ships of the Reach", "abbreviation": "SotR", "id": "11ulCOL7b73ekUSXsLnb2a77UBJq-r8TO2fhGa2Q_jX8"},
        {"title": "Solomani Front", "abbreviation": "SF", "id": "1dYRPIkVm3MWh4HJXCU2FwuwkVnVPUaxpMhk2JLddJTs"},
        {"title": "Spinward Extents", "abbreviation": "SE", "id": "1Dlp6GnL_CxxcBwJ__EoJo4LaYP3xFqsYXiIcSJj_CEs"},
        {"title": "Sword Worlds", "abbreviation": "SW", "id": "16qgktiKubW4coWI-eDppLj_w1OEgexwXWmG5Kx-9Twc"},
        {"title": "The Deep and the Dark", "abbreviation": "TDatD", "id": "1IqGTQX_TM0PyjnkBDRIxn2PVBaHkvQDZmFgvwv9hI-M"},
        {"title": "The Glorious Empire", "abbreviation": "TGE", "id": "1YgdqCXbQAl7j7wFWCx-H8No-_UqD5XDkn8Kl7YqTvSU"},
        {"title": "The Great Rift", "abbreviation": "TGR", "id": "1GcMn-AfbaZjae50I6GuOLnA-vpiAA_DQpi7_eKUiioo"},
        {"title": "The Great Rift Book 2", "abbreviation": "TGRB2", "id": "18jD6B1FH9BUdaFp7zDT7mennyhKxM1_gpFEY7B5TjsM"},
        {"title": "The Imperial Navy", "abbreviation": "TIN", "id": "11MzA7y6Dj4YyV5Q8yGzLoKNcDMf3kGQrkw2BtFo07Hk"},
        {"title": "The Third Imperium", "abbreviation": "TTI", "id": "1ThRXRhaBxuwRTy_7yfRKIbUsp28eMaOYWV88AE97fbs"},
        {"title": "Touchstone & Afawahisa", "abbreviation": "TaA", "id": "1nNMa5G0U78nldwzgqeHDFKv-BS9HwoNhHQ2h5SppZLU"},
    ],
    "Journal of the Travellers' Aid Society": [
        {"title": "Journal of the Travellers’ Aid Society 1", "abbreviation": "JTAS1", "id": "1KyLPmg_2_U0ZZ1-6IDmFFjWwPtF4jNJ_sLvvTq07kFk"},
        {"title": "Journal of the Travellers’ Aid Society 2", "abbreviation": "JTAS2", "id": "19rqIXuO2R2QB_oMzNv9qc1omsKwjb3fk-WAo_E6WT7E"},
        {"title": "Journal of the Travellers’ Aid Society 3", "abbreviation": "JTAS3", "id": "1YKYM9x_UjMjsSMxB7yIT51PIdBZF26TNCbvyFdLczho"},
        {"title": "Journal of the Travellers’ Aid Society 4", "abbreviation": "JTAS4", "id": "12PJdnOM3Yws6jz11Li9nvOO81NoIj8fAg8uNGR3wgSY"},
        {"title": "Journal of the Travellers’ Aid Society 5", "abbreviation": "JTAS5", "id": "1NJ4MhyRQpULJ6PnOLzaEofa0FLgnHa1BRbi9G_tfSG0"},
        {"title": "Journal of the Travellers’ Aid Society 6", "abbreviation": "JTAS6", "id": "1yvKWhbyszYHS3EcHYatEYsmaTmVpNnPu8_qd-tx5_fQ"},
        {"title": "Journal of the Travellers’ Aid Society 7", "abbreviation": "JTAS7", "id": "1wZOgTPlBd12IHL6Id8bq3oEOGidXmOoLSp2Q05Nn5GI"},
        {"title": "Journal of the Travellers’ Aid Society 8", "abbreviation": "JTAS8", "id": "123TtmE2wR-2r8eosY9DRUx9abP5_Sepo4M3i8Q3VNY8"},
        {"title": "Journal of the Travellers’ Aid Society 9", "abbreviation": "JTAS9", "id": "1ykaKNW2i9MDloDDeyye92eNAF6UiAFYP6mswVUHHAF0"},
        {"title": "Journal of the Travellers’ Aid Society 10", "abbreviation": "JTAS10", "id": "1VykjDu_67SBmdralI9gB6wpB_XbmjGGoIoT1r1vNU7s"},
        {"title": "Journal of the Travellers’ Aid Society 11", "abbreviation": "JTAS11", "id": "1kkajW8h9R3nr94y6pjrLJr0aetuuTHSNBNEYxnYoMT8"},
        {"title": "Journal of the Travellers’ Aid Society 12", "abbreviation": "JTAS12", "id": "1y1DxUg29klKSdp6ErIMHWNof4-g2OjuUAIpgnkq_OyI"},
        {"title": "Journal of the Travellers’ Aid Society 13", "abbreviation": "JTAS13", "id": "1X5vtlfl_Z2_EX8-OY29ddDvkdQz_MTO0TvUjhho-TNU"},
        {"title": "Journal of the Travellers’ Aid Society 14", "abbreviation": "JTAS14", "id": "10AHJT-G2mn34xBbvIzg-Fme-c-LBq_J9VCsLP9ulhcI"},
        {"title": "Journal of the Travellers’ Aid Society 15", "abbreviation": "JTAS15", "id": "1M5AsNb22X6otIlqqTGi4O5PQRfCPULfnb6fnJlgByGA"},
        {"title": "Journal of the Travellers’ Aid Society 16", "abbreviation": "JTAS16", "id": "1M6BrjwBDNGzujEw0YFshj4GkX4K-yPoKqton4hWXUNk"},
        {"title": "Journal of the Travellers’ Aid Society 17", "abbreviation": "JTAS17", "id": "14R6f9wJw3U4uogIRNggfPOKAFuGiAnvmGPnvsDIt8-g"},
        # {"title": "Journal of the Travellers’ Aid Society 18", "abbreviation": "JTAS18", "id": ""},
    ],
    "Adventures": [
        {"title": "The Calixcuel Incident", "abbreviation": "TCI", "id": "1_CkaTbbwKO5HU52QIyuMs-hS7Ei92PcWoFF1HQW0dXo"},
        {"title": "The Cordon Conflict", "abbreviation": "TCC", "id": "121-RaTGx0g6X6_QZUjg0vMuINTU03rMZQa5aef88Z6w"},
        {"title": "Death Station", "abbreviation": "DS", "id": "16sNHT3B4enXcYhI1NGlzSN1RoccupcY81inSM_4wzTw"},
        {"title": "Deepnight Endeavour", "abbreviation": "DE", "id": "1iidpqTzHz5o-5CWYVSJZFOmjRXxFRBy5zsxeXEJ47Xg"},
        {"title": "Drinax Companion", "abbreviation": "DC", "id": "1sdDAmiizfOkwWq3LFX_tMglpX1HN7Uns39AHXv2Na7I"},
        {"title": "Friends in Dry Places", "abbreviation": "FiDP", "id": "11-BzgPJuXX0uvit0Tj8qRWztfYUI_gnXqP3y45RIG0c"},
        {"title": "Gods of Marduk", "abbreviation": "GoM", "id": "1hldzrUW9nRrIbcS4KXCGWfSnBx6__t0jdD7HmgiWQOM"},
        {"title": "High and Dry", "abbreviation": "HaD", "id": "1P503eZ-NYgMA9L_UBe4kihie0cdG0dC88AKJ8JmsPVI"},
        {"title": "Liberty Port", "abbreviation": "LP", "id": "1ZnhwJUTJuzxY_5Bt9w1jE4X_YbtVAu4URWELvXiuP-M"},
        {"title": "Lions of Thebus", "abbreviation": "LoT", "id": "16-8TBZHNsIuD9GZR3Q5bn7r8N0TnJid3nXam3QvvFnE"},
        {"title": "Marooned on Marduk", "abbreviation": "MoM", "id": "1nRlgRfpcbRoFiiduMVoR5ptbK9j_Bzdbm9UxVclPzzY"},
        {"title": "Revolution on Acrid", "abbreviation": "RoA", "id": "1XHQz2TDAczSTNoU1N5uqKAVpYlOqVsPEGyRwmNYMiRM"},
        {"title": "Shadows of Sindal", "abbreviation": "SoS", "id": "1EUmaT2pRHn6vWR8USF3zVNiEGwVsGdqFc5w2jD_DthA"},
        {"title": "Skandersvik", "abbreviation": "Sk", "id": "1nxlKZDWEwFL8_BECn_XO9xN8oA4WjLkI0d210cKk2fU"},
        {"title": "Solomani Adventure 1 – Mysteries on Arcturus Station", "abbreviation": "MoAS", "id": "1ATWdpPdVj6WvCFQE8yTFtZ8jowYBzI0aycoC85mqijM"},
        {"title": "Stranded", "abbreviation": "St", "id": "1TDb8_-NEtBrgjmz1letGuTufe5bspXD8H6rpFMQb4C4"},
        {"title": "The Pirates of Drinax", "abbreviation": "TPoD", "id": "14U7EaDTxBjBfGgPjbUn93tiF-RLXPGBQvZTHtyfLgo8"},
        {"title": "The Trojan Reach", "abbreviation": "TRR", "id": "1NLn-1OVPpCupXgVB0zd20VADVamn56ezSEdP6Xcogg0"},
    ]
}
