name: Deploy to Web Server

on:
  push:
    paths:
      - 'sources/*.html'
      - 'final/*.pdf'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: copy file via ssh key
      uses: appleboy/scp-action@v0.1.7
      with:
        host: radiofreewaba.net
        username: ${{ secrets.DEPLOY_USER }}
        port: 22
        key: ${{ secrets.RFWKEY }}
        source: "static/*"
        target: ${{ secrets.DEPLOY_LOCATION }}
 
